import type { Config } from 'tailwindcss'

export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{ts,tsx}'],
  theme: {
    extend: {
      colors: {
        primary: '#506144',
        'on-primary': '#ffffff',
        'primary-container': '#687a5b',
        'on-primary-container': '#f8ffed',
        'primary-fixed': '#d5e9c4',
        'primary-fixed-dim': '#b9cda9',
        'on-primary-fixed': '#111f08',
        'on-primary-fixed-variant': '#3b4b30',
        'inverse-primary': '#b9cda9',
        secondary: '#556347',
        'on-secondary': '#ffffff',
        'secondary-container': '#d9e8c5',
        'on-secondary-container': '#5b694d',
        'secondary-fixed': '#d9e8c5',
        'secondary-fixed-dim': '#bdccaa',
        'on-secondary-fixed': '#131f09',
        'on-secondary-fixed-variant': '#3e4b31',
        tertiary: '#715822',
        'on-tertiary': '#ffffff',
        'tertiary-container': '#8b7138',
        'on-tertiary-container': '#fffbff',
        'tertiary-fixed': '#ffdf9f',
        'tertiary-fixed-dim': '#e3c281',
        'on-tertiary-fixed': '#261a00',
        'on-tertiary-fixed-variant': '#5a430e',
        error: '#ba1a1a',
        'on-error': '#ffffff',
        'error-container': '#ffdad6',
        'on-error-container': '#93000a',
        surface: '#fbf9f4',
        'surface-dim': '#dbdad5',
        'surface-bright': '#fbf9f4',
        'surface-container-lowest': '#ffffff',
        'surface-container-low': '#f5f3ee',
        'surface-container': '#f0eee9',
        'surface-container-high': '#eae8e3',
        'surface-container-highest': '#e4e2dd',
        'on-surface': '#1b1c19',
        'on-surface-variant': '#444840',
        'inverse-surface': '#30312e',
        'inverse-on-surface': '#f2f1ec',
        outline: '#75786f',
        'outline-variant': '#c5c8bd',
        'surface-tint': '#526346',
        background: '#fbf9f4',
        'on-background': '#1b1c19',
        'surface-variant': '#e4e2dd',
        'text-primary': '#1F211D',
        'text-secondary': '#8C8A83',
        'border-subtle': '#E5E2DA',
        'surface-card': '#FFFFFF',
        'action-hover': '#DDE7CF',
        'status-success': '#7B8F6B',
        'status-danger': '#B45A5A',
        'dark-bg': '#141512',
        'dark-surface': '#1C1E1A',
        'dark-border': '#31342E',
        'dark-text-primary': '#F3F1EA',
      },
      spacing: {
        unit: '4px',
        gutter: '32px',
        'margin-safe': '64px',
        'section-gap': '128px',
        'container-max': '1440px',
      },
      maxWidth: {
        'container-max': '1440px',
      },
      fontFamily: {
        'display-xl': ['Cormorant Garamond', 'serif'],
        'display-xl-mobile': ['Cormorant Garamond', 'serif'],
        'headline-lg': ['Cormorant Garamond', 'serif'],
        'headline-md': ['Cormorant Garamond', 'serif'],
        'body-lg': ['EB Garamond', 'serif'],
        'body-md': ['EB Garamond', 'serif'],
        'label-sm': ['Inter', 'sans-serif'],
        'nav-link': ['Inter', 'sans-serif'],
      },
      fontSize: {
        'display-xl': ['80px', { lineHeight: '1.1', letterSpacing: '-0.02em', fontWeight: '600' }],
        'display-xl-mobile': ['48px', { lineHeight: '1.1', fontWeight: '600' }],
        'headline-lg': ['48px', { lineHeight: '1.2', fontWeight: '500' }],
        'headline-md': ['32px', { lineHeight: '1.3', fontWeight: '500' }],
        'body-lg': ['22px', { lineHeight: '1.8', fontWeight: '400' }],
        'body-md': ['18px', { lineHeight: '1.7', fontWeight: '400' }],
        'label-sm': ['12px', { lineHeight: '1.5', letterSpacing: '0.15em', fontWeight: '500' }],
        'nav-link': ['13px', { lineHeight: '1.0', letterSpacing: '0.1em', fontWeight: '400' }],
      },
      borderRadius: {
        DEFAULT: '0',
        none: '0',
        sm: '0',
        md: '0',
        lg: '0',
        xl: '0',
        '2xl': '0',
        '3xl': '0',
        full: '0',
      },
      scale: {
        '102': '1.02',
      },
    },
  },
  plugins: [],
} satisfies Config
